version: "3.7"

services:
    app:
        build: .
        command: rails s
        ports:
            - 3000:3000
        volumes:
            - .:/app
        depends_on:
            - db
    db:
        image: postgres
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: password

